//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBEPAEscritorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ConexionInicialServer {
            get {
                return ((string)(this["ConexionInicialServer"]));
            }
            set {
                this["ConexionInicialServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string ConexionInicialPuerto {
            get {
                return ((string)(this["ConexionInicialPuerto"]));
            }
            set {
                this["ConexionInicialPuerto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJpdiI6ImtTWVVGMThYTi9OTkhsc0p3cXZJbFE9PSIsInZhbHVlIjoiQ01FRUtaUzJwNEk0dXAzOEpyT" +
            "UZpTWdxS01GOW1hQjJNK2RsWkJMYTNrRT0iLCJtYWMiOiI0MjY5YjFiZGM0YTdiMjE5ZDlhZGEyNTdjY" +
            "TYxNTQzNWMwMTlkYTkzMDk3NmUxMjdhMzI0NjBmODUzMWVkY2Y1In0=")]
        public string ConexionInicialUsuario {
            get {
                return ((string)(this["ConexionInicialUsuario"]));
            }
            set {
                this["ConexionInicialUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJpdiI6IjVRUHR4eTZaVmhURGpOTi9IVytlb2c9PSIsInZhbHVlIjoiUDMvRDZaSjZuYk1FOGtQeEk2W" +
            "m9rUHVIZmx5SEg0K05hNkdZRjZuZThBVT0iLCJtYWMiOiJhMDk3MGRlMGQ2MGZkOGMxYTliMjZjMGQxM" +
            "WJiN2Y0YTQ5NTI5M2NlNGM5NTg5NmI4OWJkYmI2N2NlOTE3MGU3In0=")]
        public string ConexionInicialClave {
            get {
                return ((string)(this["ConexionInicialClave"]));
            }
            set {
                this["ConexionInicialClave"] = value;
            }
        }
    }
}
